### ISSUE TITLE
Use arithmetic average from * to *****.

### ISSUE THREAD

**Issue by alexfernandez** [alexfernandez/package-quality#11]
The results for geometric and harmonic averages are not acceptable: they violate the universal values for [star ratings](http://xkcd.com/1098/) since most packages have zero (and not 1~3). We should use an arithmetic average, with the same weights as now, and start with one star.

**Comment by tufosa** [comment]
Tested in app_no_mongo. Waiting for mongo to update before closing the issue.

**Comment by tufosa** [comment]
DB updated with arithmetic average. Closing.
