### ISSUE TITLE
Unite no_mongo and mongo

### ISSUE THREAD

**Issue by alexfernandez** [alexfernandez/package-quality#15]
Currently there are two versions of the site:

* mongo uses MongoDB to read package information,
* no_mongo queries GitHub and other datasources concurrently and gets an answer, so the package is checked online.

It would be great to have a single, unified version that uses cached information, and if it's outdated checks online.

In addition to the date, package information might contain a `version` field checked by the server: if earlier than a given version it is considered outdated and checked online.

**Comment by tufosa** [comment]
Great idea!! This new version should replace the "mongo" version. "No-mongo" will still be useful to launch for debug purposes. The new "mongo" version should work as follows:
    - if the entry is in the DB:
        - if it is outdated:
                - fetch data from the Internet, update DB and serve. If no remaining API calls left, store entry in "update" collection and serve outdated
        - else (entry IN the database and NOT updated):
                - serve
     - else (entry NOT in the database):
         - fetch data from the Internet, update DB and serve. If no remaining API calls left, store entry in "update" collection and serve error

**Comment by alexfernandez** [comment]
I think this is already solved with the recent https://github.com/alexfernandez/package-quality/pull/36, closing.
