### ISSUE TITLE
Simple badges

### ISSUE THREAD

**Issue by matiassingers** [alexfernandez/package-quality#25]
Awesome idea!

I would suggest a simpler badge design in addition to the current one. I know a lot of people use the [shields.io](http://shields.io/) style badges in their packages, and putting the current package-quality badge next to them doesn't look very well.

Would also be awesome with the same styles as shields.io:
![](https://img.shields.io/badge/style-plastic-green.svg?style=plastic)
![](https://img.shields.io/badge/style-flat-green.svg?style=flat)
![](https://img.shields.io/badge/style-flat--squared-green.svg?style=flat-square)

**Comment by alexfernandez** [comment]
Great idea! Would something like this be cool? https://img.shields.io/badge/quality-%E2%98%85%E2%98%85%E2%98%85%C2%BD%E2%98%86-green.svg I guess that common practice is just redirect to shield.io to get the image?

**Comment by matiassingers** [comment]
@alexfernandez yeah that would be super awesome!

Yeah I think a lot of services basically just redirect to shields.io.

**Comment by alexfernandez** [comment]
There are some issues: [custom support might be useful](https://github.com/badges/shields/issues/397), [Unicode does not work in PNG](https://github.com/badges/shields/issues/396). Working on them.

**Comment by matiassingers** [comment]
Oh too bad about the unicode in PNG, but awesome man!

Great work!

**Comment by rottmann** [comment]
:+1:

**Comment by alexfernandez** [comment]
Done, [example](http://npm.packagequality.com/shield/express.svg).

**Comment by matiassingers** [comment]
So awesome! :+1: :+1:
