### ISSUE TITLE
Packages Not Found

### ISSUE THREAD

**Issue by anywhichway** [alexfernandez/package-quality#31]
I am getting package not found errors for npm packages that are published and are on Github. Try two of mine: stringformatter and propertyinterceptor.

I'm new to publishing using npm, so perhaps the quality of my publishing is so bad, you can't read them!

**Comment by alexfernandez** [comment]
Hi, currently it takes a week to refresh the complete list of packages. There is an open issue to get packages on demand: https://github.com/alexfernandez/package-quality/issues/15.
