### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by arynhard** [alexfernandez/package-quality#39]
I would like to look at the "quality" of my package. Unfortunately `packagequality.com` says it could not find it.

**Comment by sgmonda** [comment]
Hi @arynhard,
Which is your missing package?

**Comment by arynhard** [comment]
@sgmonda: https://atom.io/packages/texlicious

**Comment by tufosa** [comment]
Hi Andrew,

we are only evaluating npm packages so far. Anything that is not in
npmjs.com, will not be found in packagequality.com.

cheers,

Diego.

**Comment by arynhard** [comment]
@tufosa: thanks.

**Comment by alexfernandez** [comment]
Needless to say, patches to support other package managers are welcome :)
