### ISSUE TITLE
Problem with badge

### ISSUE THREAD

**Issue by coderaiser** [alexfernandez/package-quality#40]
![image](https://cloud.githubusercontent.com/assets/1573141/10012374/1d34d2ce-6110-11e5-90bb-649262ce0df1.png)

**Comment by alexfernandez** [comment]
Thanks for the report, we will take a look.

**Comment by alexfernandez** [comment]
@tufosa, the [badge](http://npm.packagequality.com/shield/package-quality.svg) on the [homepage](https://github.com/alexfernandez/package-quality) suddenly looks weird. However the [raw badge](https://img.shields.io/badge/quality-%E2%98%85%E2%98%85%E2%98%85%E2%98%85%E2%98%85-brightgreen.svg) looks fine. Any clues?

**Comment by DiegoTUI** [comment]
@alexfernandez I am not very familiar with the badges. I've checked the API part and it seems to be working OK. @sgmonda any clue?

**Comment by DiegoTUI** [comment]
@alexfernandez @sgmonda and anyway, in the [homepage](https://github.com/alexfernandez/package-quality) it looks fine.

**Comment by alexfernandez** [comment]
Not for me on Debian, is it a Linux-specific thing? See: 
![captura de pantalla - 230915 - 09 40 13](https://cloud.githubusercontent.com/assets/876570/10039935/268cffbe-61d7-11e5-833f-928bc77a2798.png)

**Comment by DiegoTUI** [comment]
I've tried it on Safari, Firefox and Chrome (Mac OSX). Looks fine in all of them. I've tried in Ubuntu and it fails, but only in Chrome (in Firefox it works fine). Seems like the font we are using (DejaVu Sans,Verdana,Geneva,sans-serif) is not loaded in Chrome.
![screen shot 2015-09-23 at 09 42 52](https://cloud.githubusercontent.com/assets/3273576/10039989/b4d93382-61d7-11e5-8952-5392246b962f.png)

**Comment by alexfernandez** [comment]
Woah, it has fixed itself magically! Had to reload with shift so that images were also reloaded. Closing, thanks!

**Comment by DiegoTUI** [comment]
Software engineering is 60% skills, 40% magic. Well done!!
