### ISSUE TITLE
Badge shows weird characters

### ISSUE THREAD

**Issue by fcanela** [alexfernandez/package-quality#41]
Interesting project :+1: . Having something like this would be hanging when deciding if a dependency is worth being added or removed.

Well, let's not start sucking each other's dicks quite yet. Badges shows a weird text.

![badge](https://cloud.githubusercontent.com/assets/1985394/10219390/d4d094f6-683e-11e5-974d-85df0b32a02f.png)

Tested with Firefox 41 and Chrome 45 under Ubuntu 14.04.

Looking the code, it seems like you try to place the ASCII (filled or unfilled) stars in SVG but it's not well encoded at server side or decoded at client one. The "one half" character have no issues.

I'll try to help with it if I've time and nobody solves it before.

**Comment by alexfernandez** [comment]
This issue has been reported before here: https://github.com/alexfernandez/package-quality/issues/40, but @DiegoTUI could not pinpoint it. Please take a look. If you can find it and solve it, you will be my hero!

**Comment by fcanela** [comment]
Sorry, I did not found it. I solved it locally. Placing the alt code (&#9733; and &#9734;) instead of the character outputs it correctly. I'll try to send a PR during the day.

**Comment by alexfernandez** [comment]
Great!

Alex.

**Comment by fcanela** [comment]
I still have this in my TODO list. It's being a busy week.

**Comment by fcanela** [comment]
After giving a quick check before going to sleep, I learnt a little bit more about package-quality and the problem.

Placing the unicode code would be the solution if it was package-quality who rendered the svg, but it acts as a proxy with shields.io.

It request the image passing stars as part of the url to shields.io. After some use of wireshark, I found that the **url is not correctly encoded** before doing the request, being the correct request something like: [https://img.shields.io/badge/quality-%E2%98%85%E2%98%85%E2%98%85%E2%98%85%C2%BD-green.svg]

I already had the changes done in local, but somehow I am unable to test it due some database error which I do not feel like configuring at 1 a.m. I will finish it when I have enough time, I just wanted to report the cause and the solution meanwhile.

**Comment by alexfernandez** [comment]
Great job! Awaiting your patch :)

**Comment by alexfernandez** [comment]
Changed in version 0.2.3. @DiegoTUI, can you please it deploy it to package-quality.com?

Thanks, @fcanela, for the report and the solution!
