### ISSUE TITLE
Different results

### ISSUE THREAD

**Issue by NeXTs** [alexfernandez/package-quality#43]
Take a look at measurements for [clusterize.js package](http://packagequality.com/#?package=clusterize.js)
Shield's and badge's stars vary

![packageq](https://cloud.githubusercontent.com/assets/1753208/11607361/1e942806-9b4c-11e5-8b32-a2d698253851.png)

I suspect it's because badge fetch [clusterize](http://packagequality.com/#?package=clusterize) package instead of clusterize.js

**Comment by NeXTs** [comment]
Any updates on this?

**Comment by alexfernandez** [comment]
Sorry for the delay, I think it's [solved](http://packagequality.com/#?package=clusterize.js) now. Can you check?

**Comment by NeXTs** [comment]
:+1: thank you!

**Comment by alexfernandez** [comment]
Thanks for the report! :)
