### ISSUE TITLE
inadequate rating

### ISSUE THREAD

**Issue by vitaly-t** [alexfernandez/package-quality#44]
Just out of curiosity I tried with one of my packages, pg-promise

It dropped the rating a lot based on the number of issues that were open over the package's lifespan.

A popular, high-quality package will naturally receive much attention, and much of that attention is in questions and ideas people bring to the table. In my project all questions have been answered and all ideas have been met, no issues open at all, and yet the rating is dropped because there were questions and ideas published on GitHub? This is nonsense. This absolutely does not reflect the package's quality.

**Comment by DiegoTUI** [comment]
You are definitely right in one thing. There is still a lot of room for improving the way we rate the packages. You are welcome to add your own rating factor and submit a PR. Regarding the way we compute issues, here's an explanation of how it is done so far (you can have a look yourself in lib/factors/isssues):
- we get all the issues of the packages (```total```)
- out of ```total``` we store in ```open``` those that are still open
- out of ```total``` we store in ```closed``` those that are already closed
- out of ```open``` we store in ```longOpen```those issues that have been open for more than a year
- then we compute this three factors:
``` 
var totalFactor = 1 - 1 / total;
var openFactor = (open / total > 0.2) ? 1.2 - open / total : 1;
var longOpenFactor = (open > 0) ? 1 - longOpen / open : 1;
```
and we use the average of these three factors to compose the issues factor. This issues factor is combined with other two (downloads and versions) to come up with the final quality score.

and BTW, your package gets a 99.7% quality score.

http://packagequality.com/#?package=pg-promise 

Honestly, it can't get much better than that ;-))

**Comment by vitaly-t** [comment]
>and BTW, your package gets a 99.7% quality score.

That is not the score that I saw yesterday, it was way lower. That's why I wrote all this. But it changed since. I don't understand why.... I was getting something like 85% on the Open Issues.

**Comment by alexfernandez** [comment]
Maybe you closed some longstanding issues? Quality is recomputed every day.

**Comment by vitaly-t** [comment]
Nope, I did not, and I did not have any outstanding issues.

**Comment by vitaly-t** [comment]
Closing as an unresolved mystery.

**Comment by tufosa** [comment]
;-))
