### ISSUE TITLE
Add retina support (banner) 

### ISSUE THREAD

**Issue by equinusocio** [alexfernandez/package-quality#46]
Add a retina ready quality banner. Now the banner looks like a s**t on retina display :)

**Comment by alexfernandez** [comment]
Care to propose a patch?

**Comment by equinusocio** [comment]
How?

**Comment by alexfernandez** [comment]
We would need to know why it looks wrong. The [existing banner](https://camo.githubusercontent.com/4d91886bebbf0f1f2b67778a19c36c411980d201/687474703a2f2f7061636b6167657175616c6974792e636f6d2f736869656c642f7061636b6167652d7175616c6974792e737667) is a SVG so it should scale nicely.

Can you attach a screenshot and a link so we can diagnose the problem first?

**Comment by equinusocio** [comment]
Not the shield, i mean the banner:
<img width="287" alt="screen shot 2016-09-12 at 10 49 36" src="https://cloud.githubusercontent.com/assets/10454741/18429958/a06d5f6a-78d6-11e6-9def-58fa106729d0.png">

**Comment by alexfernandez** [comment]
Wow, you are right. @tufosa Do you think we can improve it?

**Comment by tufosa** [comment]
Looks pretty bad. It wasn't me who implemented the client side. Let me have
a look at how it's done and see if There is an easy fix.

**Comment by alexfernandez** [comment]
Was it @sgmonda? What do you think, Sergio?

**Comment by DiegoTUI** [comment]
@alexfernandez @sgmonda it seems like we need a higher quality app/img/badge2.png, as well as higher quality stars. As @equinusocio pointed out, an easy fix would be to replace our current image resources by 3x quality resources and serve them for all devices. A fine tune of this approach would be to have several quality of images for several resolutions, read the user-agent of the request and serve accordingly.
@sgmonda can you provide higher quality images of the badge and stars?

**Comment by sgmonda** [comment]
@DiegoTUI @alexfernandez @tufosa  I've added x2 and x3 versions for badge and stars, and I've implemented a simple way to serve x2 and x3 images, just adding an optional argument `size=X` to the badge URL. 
Example:

http://npm.packagequality.com/badge/material-theme.png
![image](https://cloud.githubusercontent.com/assets/675812/18611658/e265440a-7d40-11e6-98b0-d11970c3ac6b.png)

http://npm.packagequality.com/badge/material-theme.png?size=2
![image](https://cloud.githubusercontent.com/assets/675812/18611660/e9fc672a-7d40-11e6-9fce-62834e52178e.png)

http://npm.packagequality.com/badge/material-theme.png?size=3
![image](https://cloud.githubusercontent.com/assets/675812/18611661/f1eca666-7d40-11e6-9ca8-0e9433fefd2a.png)

I'll leave checking the user agent (or other tricks to avoid having to write the "size" argument) in your hands.
**NOTE** I'm not able to deploy to production. This improvement is pushed but not deployed. Please do it for me. Thanks.

**Comment by DiegoTUI** [comment]
thanks @sgmonda. I just deployed this last version. Closing the issue.

**Comment by DiegoTUI** [comment]
Well, I can't close the issue ;-)) @alexfernandez please, test the new features and close it.

**Comment by alexfernandez** [comment]
I cannot test it, @equinusocio can you let us know if it works for you, or do you need anything else?

**Comment by equinusocio** [comment]
I see yet the non-retina banner.

**Comment by DiegoTUI** [comment]
@equinusocio are you adding the size parameter to your request? I just checked right now and it seems like it's working:

http://packagequality.com/badge/async.png?size=3

**Comment by equinusocio** [comment]
But shouldn't be automatic?

**Comment by thecotne** [comment]
why not serve svg?

**Comment by alexfernandez** [comment]
Not sure that we have `svg` for that particular image, but it might be a good solution. @sgmonda, what do you think?

**Comment by thecotne** [comment]
to help decide about `svg` here are benefits of it

- Extremely High Quality (Retina ready, One Size fits all)
- Extremely Low Size
- Easy to generate with script

**Comment by equinusocio** [comment]
> • Extremely Low Size

False. It is not always so.

**Comment by thecotne** [comment]
minimize "any" svg with [svgo](https://github.com/svg/svgo)
take that svg and convert to png and compere size

svg is always smaller then png/jpeg

if you have vector graphics in first place (like stars and check mark ...)
i am not saying converting png/jpeg to svg will save you size

**Comment by thecotne** [comment]
if you drow [this](https://github.com/alexfernandez/package-quality/blob/master/app/img/badge2_x3.png) in illustrator/inkscape it will be much smaller and much better quality

**Comment by equinusocio** [comment]
> if you have vector graphics in first place (like stars and check mark ...)
i am not saying converting png/jpeg to svg will save you size

👍

**Comment by alexfernandez** [comment]
Good idea. Any takers? @equinusocio @thecotne?

**Comment by thecotne** [comment]
@alexfernandez everything looks simple in `badge2.psd` but logo is not vector
do you have vector version of logo? `svg` or `ai` format?

@equinusocio you can minimize svg with [svgo](https://github.com/svg/svgo) and compress with gzip

**Comment by alexfernandez** [comment]
I do not think we have a SVG version, but I will let @sgmonda answer the question.

**Comment by thecotne** [comment]
ping @alexfernandez @sgmonda

**Comment by sgmonda** [comment]
There is no `svg` version of our image resources. Even if we create it, we cannot support `svg` badges right now, unless we change the way we build them. We're using a virtual canvas which needs the width and height to compute the final image. That is the reason we've added support for `size` argument, which just multiplies by 2 or 3 the original size.

Supporting `svg` badges is a good feature, but nothing trivial right now.

**Comment by thecotne** [comment]
If you guys provide vector logo i can  create svg version of badge and
generator script for that

**Comment by alexfernandez** [comment]
@thecotne We just don't have it. Is anyone able to replicate it in vector form? That would be cool!

**Comment by Wandmalfarbe** [comment]
I created the logo in vector format (Inkscape-SVG) here #48.

**Comment by alexfernandez** [comment]
Thanks, @Wandmalfarbe, merged now! @thecotne can you pick it up from here?

**Comment by thecotne** [comment]
working on it ...

**Comment by thecotne** [comment]
sorry for delay ...


so far i have this -> https://gist.github.com/thecotne/2a0776c6849cee2ddfbb3b35bc7ac119

(half star has different style)

i could not start package quality locally ...
it wants some mongodb running ...

```
[Sun Apr 09 2017 22:19:53 GMT+0400 (+04)] NOTICE local-config.js not found
[Sun Apr 09 2017 22:19:54 GMT+0400 (+04)] INFO Server listening on port 8080
[Sun Apr 09 2017 22:19:54 GMT+0400 (+04)] ERROR Could not connect to MongoDB: MongoError: failed to connect to server [localhost:27017] on first connect


```

**Comment by alexfernandez** [comment]
Not bad. Can you send a PR?

**Comment by equinusocio** [comment]
@thecotne The green mark is not vertically centered :)

**Comment by thecotne** [comment]
@equinusocio updated ...

green color was also wrong
