### ISSUE TITLE
Can't find jquery.terminal

### ISSUE THREAD

**Issue by jcubic** [alexfernandez/package-quality#47]
I have a package [jquery.terminal](https://www.npmjs.com/package/jquery.terminal) but when I search I only get bioship.jquery.terminal. the package can be found by changing the url to http://packagequality.com/#?package=jquery.terminal

**Comment by thecotne** [comment]
it's searchable for me 
<img width="519" alt="screenshot 2017-02-26 21 28 00" src="https://cloud.githubusercontent.com/assets/1606993/23341951/81992e26-fc6a-11e6-85b9-38b5b27ac35f.png">

**Comment by jcubic** [comment]
When I reported the issue only bioship was present, it work now.
