### ISSUE TITLE
https please

### ISSUE THREAD

**Issue by corysimmons** [alexfernandez/package-quality#50]
Your badge is still served from http.

https://www.i18next.com/ console:

![image](https://cloud.githubusercontent.com/assets/224636/26686085/ecca465a-46b9-11e7-867c-6d754188e156.png)

**Comment by alexfernandez** [comment]
You are right, this is a bit stinky. Care to propose a pull request?

**Comment by corysimmons** [comment]
I'm far too lazy to do anything other than point out things.

**Comment by alexfernandez** [comment]
Fair enough, will get to it eventually!

**Comment by corysimmons** [comment]
No problem. tbh I just file things as I notice them. I'm a lazy/unpaid QA person for projects I find interesting.

**Comment by alexfernandez** [comment]
Your efforts are much appreciated!

**Comment by Ehesp** [comment]
Also looking for https, currently this is the only thing on our Github hosted site blocking it from full https :(

**Comment by alexfernandez** [comment]
@DiegoTUI Can we open port 443 and serve badges from there? Thanks!

**Comment by DiegoTUI** [comment]
Yep!! Will do today!!

**Comment by DiegoTUI** [comment]
done, @corysimmons @Ehesp can you check?

**Comment by corysimmons** [comment]
![image](https://user-images.githubusercontent.com/224636/28094746-622789f4-666c-11e7-8b7e-94187c407a97.png)

Not sure if I'm checking wrong or what. Just go to i18next.com and check out the console:

![image](https://user-images.githubusercontent.com/224636/28094766-8970914a-666c-11e7-82a7-ead94b56d8ec.png)

**Comment by tufosa** [comment]
mmmmmmmhhh.... That's because letsencrypt does no issue wilcard
certificates yet. And I got one for packagequality.com, but not for
npm.package.com. Will try something else tonight.

**Comment by DiegoTUI** [comment]
@corysimmons I expended the certificate to npm.packagequality.com. Can you try again?

**Comment by Ehesp** [comment]
Horray :) https://npm.packagequality.com/shield/react-native-firebase.svg?style=flat-square

**Comment by corysimmons** [comment]
![](https://m.popkey.co/ab40c8/qr9WA_s-200x150.gif)
