### ISSUE TITLE
Wrong npm package?

### ISSUE THREAD

**Issue by corysimmons** [alexfernandez/package-quality#51]
http://packagequality.com/#?package=lost

![image](https://user-images.githubusercontent.com/224636/27930112-6aa6bce2-6263-11e7-98ff-254f742dfaf2.png)

![image](https://user-images.githubusercontent.com/224636/27930117-715aee50-6263-11e7-90e4-df2c2a700a04.png)

![image](https://user-images.githubusercontent.com/224636/27930124-78130976-6263-11e7-88e6-7f11f42a3baa.png)

Is package-quality rating an old package or something? `lost` has been around for a few years as a grid (not as a "cache everything" although I may have got the npm pkg name from someone).

Still though... few years.

**Comment by alexfernandez** [comment]
What should it show?

**Comment by corysimmons** [comment]
Where it says "Cache everything" it should say something along the lines of "LostGrid is a powerful grid system built..."

I believe you're displaying cached pkg metadata. Perhaps it would be better to fetch pkg data on demand?

Or at least cache the metadata every month or so instead of multiple years.

Am I right in assuming this is what's going on?

**Comment by corysimmons** [comment]
Oh it looks like it has been updated (for that pkg anyway).

![image](https://user-images.githubusercontent.com/224636/28253684-51787b8e-6a74-11e7-9449-064d1c39f74f.png)

🤷‍♂️
