### ISSUE TITLE
Wrong data when npm package name contains a dot

### ISSUE THREAD

**Issue by dpilafian** [alexfernandez/package-quality#55]
The page for the **dna.js** project shows metadata from the **dna-js** project.

![packagequality](https://user-images.githubusercontent.com/119555/33052144-4b163256-ce22-11e7-8f7b-240a536461e1.png)

The tag line for:
http://packagequality.com/#?package=dna.js
displays:
`Human friendly data format.`

It should display:
`An uncomplicated user interface library for semantic templates`
as can be seen on the **dna.js** npm page:
https://www.npmjs.com/package/dna.js

Note that the tag line for:
http://packagequality.com/#?package=dna-js
correctly displays:
`Human friendly data format.`

**Comment by alexfernandez** [comment]
@DiegoTUI Any clues?

**Comment by tufosa** [comment]
It seems like we are receiving errors while trying to re-estimate a
package. Will try to fix it this week.

**Comment by DiegoTUI** [comment]
I believe it is fixed now. @dpilafian can you check?
