### ISSUE TITLE
Support Scoped Packages (i.e. `@google`)

### ISSUE THREAD

**Issue by grant** [alexfernandez/package-quality#56]
Packages that are scoped (Use `@`) break the image URL:
http://npm.packagequality.com/#?package=@google%2Fclasp

**Comment by alexfernandez** [comment]
Hi, sorry for the delay! It sounds good, care to venture a patch?

**Comment by alexfernandez** [comment]
That is cool! If you propose a PR I will just accept it.

**Comment by grant** [comment]
It looks like this repo ignores `local-config.js`.

I also get the error:
```js
/Users/granttimmerman/Documents/github/grant/package-quality/test.js:21
	log.debug('Running tests');
	    ^
TypeError: log.debug is not a function
```

**Comment by alexfernandez** [comment]
Again, I would appreciate it if you can submit a PR :smile:

**Comment by grant** [comment]
Well, I'd submit a PR for the feature if the project build wasn't broken.

I can't say I'm going to (1) fix the project build, then (2) add a PR, since there's a fine workaround.

**Comment by alexfernandez** [comment]
Fair enough, I will try to repair the build and get back to you, OK?

**Comment by sasadjolic** [comment]
Any updates on adding support for scoped packages?

**Comment by sasadjolic** [comment]
I should mention that the workaround as described above in the history of this issue does not work anymore

**Comment by grant** [comment]
I added a PR that I believe fixes the URL rendered on the web page. Although I don't know if it fixes the related/new searching issue.

**Comment by alexfernandez** [comment]
Merged and restarted! But now https://packagequality.com/shield/%40google%2Fclasp.svg is yielding an error :thinking:
