### ISSUE TITLE
Badge in GH is not updated after quality updated

### ISSUE THREAD

**Issue by oleg-koval** [alexfernandez/package-quality#58]
my gh badge: 
[![Package Quality][pq-image]][pq-link]

quality report: http://packagequality.com/#?package=koa-verto

badge in npm package page is ok

[pq-image]:http://npm.packagequality.com/shield/koa-verto.svg
[pq-link]:http://packagequality.com/#?package=koa-verto

**Comment by alexfernandez** [comment]
Great! Closing, feel free to reopen if needed.

**Comment by alexfernandez** [comment]
OK, will look into it.

**Comment by alexfernandez** [comment]
What is the difference? I see the same thing in both places.
![image](https://user-images.githubusercontent.com/876570/46415088-d28ce800-c724-11e8-9940-8610915a6a84.png)

Keep in mind that GitHub caches images for a certain time.

**Comment by oleg-koval** [comment]
true, you right, closing this :) 
thanks!
