### ISSUE TITLE
badge on GH doesn't match to the SVG 

### ISSUE THREAD

**Issue by Junior2Ran** [alexfernandez/package-quality#59]
This issue seems to be similar to #58 

The quality on website is 4 stars, [check it here](http://packagequality.com/#?package=vis-ui)
But the badege appears 2.5 stars on GITHUB
 [![Package Quality](http://npm.packagequality.com/shield/vis-ui.svg)](http://packagequality.com/#?package=vis-ui)
However, the [svg image](http://npm.packagequality.com/shield/vis-ui.svg) seems correct on an independent browser label

I have cleared my browser cache and cookies, but the problem still exists. I wonder why does it happen? 🤣 

Here is my repo [vis-ui](https://github.com/huiyan-fe/vis-ui).

**Comment by Junior2Ran** [comment]
It turns ok today. Maybe the problem is due to GH caches? No way to prove...

**Comment by Junior2Ran** [comment]
It goes wrong again... 🤣 So it can't be GH caches reason. Somebody to find it out?

**Comment by alexfernandez** [comment]
Sure! I am reading 4 stars both on the repo and on the badge itself. Perhaps there is a dirty cache somewhere?

**Comment by Junior2Ran** [comment]
OMG, 4 stars again~ I'm gonna just leave it, damn cache! 😵

**Comment by alexfernandez** [comment]
Sorry about that! I will review this issue to be sure the next time I delve into the repo.

**Comment by Junior2Ran** [comment]
It's ok. It might not be caused by the repo. GH cache may be the key reason.
