### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by jackmu95** [alexfernandez/package-quality#62]
The SSL certificate on https://packagequality.com/ is expired since June 26.
It would be awesome to have the LetsEncrypt certificate renewed to be able to browse the site safely again.

The expired certificate also causes badges to fail loading when requested over HTTPS
![Bildschirmfoto 2020-07-21 um 15 21 32](https://user-images.githubusercontent.com/2737132/88060201-34227e80-cb66-11ea-9981-8f66fd93dece.png)

**Comment by alexfernandez** [comment]
Certificate renewed. I have also set up `certbot` to automate renewals. Thanks a lot! :+1:
