### ISSUE TITLE
Show all quality factors

### ISSUE THREAD

**Issue by alexfernandez** [alexfernandez/package-quality#7]
When a package has a GitHub repo but no issues, it shows with quality factors null. It should show which quality factor has actually lowered its score to zero, for improved transparency.

Sample: [microprofiler](http://packagequality.com:8080/microprofiler).
```
{
"_id":"54cad1fd465dcde6761d2b96",
"name":"microprofiler",
"source":"npm",
"repoQuality":0,
"repoFactors":null,
"quality":0,
"created":"2015-02-06T04:27:50+00:00",
"lastUpdated":"2015-02-06T04:27:50+00:00",
"nextUpdate":"2015-03-06T04:27:50+00:00",
"timesUpdated":0
}
```

**Comment by tufosa** [comment]
solved in last merge
